spring:
  datasource:
    url: jdbc:h2:~/soulmate
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource-platform: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

kakao:
  client-id: 538bf1cff0878d491d658580a390e409
  redirect-uri: http://localhost:8080/oauth/kakao/callback
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret: w9X!m73G2n@QvLd*BfP#8VzYkRu6EeZ^tA1oJz$L
